#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt SHARE_HISTORY

#if [[ -s "${ZDOTDIR:-$HOME}/.zsh/alias.zsh" ]]; then
#    source "${ZDOTDIR:-$HOME}/.zsh/alias.zsh"
#fi
#

for i in ${ZDOTDIT:-${HOME}}/.zsh/*.zsh ; do
    source ${i}
done

